/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'cash' : IDL.Null,
  'wallet' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'workerId' : IDL.Nat,
  'paymentMethod' : PaymentMethod,
  'jobId' : IDL.Nat,
  'customerId' : IDL.Principal,
  'totalPrice' : IDL.Nat,
});
export const RateType = IDL.Variant({
  'perday' : IDL.Null,
  'sqft' : IDL.Null,
  'runningft' : IDL.Null,
});
export const Worker = IDL.Record({
  'id' : IDL.Nat,
  'workType' : IDL.Text,
  'owner' : IDL.Principal,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'experience' : IDL.Nat,
  'mobile' : IDL.Text,
  'rateAmount' : IDL.Nat,
  'rateType' : RateType,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Rating = IDL.Record({
  'review' : IDL.Text,
  'workerId' : IDL.Nat,
  'bookingId' : IDL.Nat,
  'stars' : IDL.Nat,
  'customerId' : IDL.Principal,
});
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'workType' : IDL.Text,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'areaSqft' : IDL.Nat,
  'customerId' : IDL.Principal,
  'calculatedPrice' : IDL.Nat,
  'startDate' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRating' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'adminGetPlatformStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalWorkers' : IDL.Nat,
          'totalBookings' : IDL.Nat,
          'completedBookings' : IDL.Nat,
          'totalRevenue' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'adminListAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'adminListAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculatePrice' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], ['query']),
  'createBooking' : IDL.Func([IDL.Nat, IDL.Nat, PaymentMethod], [IDL.Nat], []),
  'createJob' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkerAverageRating' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Float64)],
      ['query'],
    ),
  'getWorkerRatings' : IDL.Func([IDL.Nat], [IDL.Vec(Rating)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBookingsByCustomer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'listBookingsByWorker' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'listJobsByCustomer' : IDL.Func([IDL.Principal], [IDL.Vec(Job)], ['query']),
  'listWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'listWorkersByType' : IDL.Func([IDL.Text], [IDL.Vec(Worker)], ['query']),
  'registerWorker' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, RateType, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, Status], [], []),
  'updateWorker' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        RateType,
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'cash' : IDL.Null,
    'wallet' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'workerId' : IDL.Nat,
    'paymentMethod' : PaymentMethod,
    'jobId' : IDL.Nat,
    'customerId' : IDL.Principal,
    'totalPrice' : IDL.Nat,
  });
  const RateType = IDL.Variant({
    'perday' : IDL.Null,
    'sqft' : IDL.Null,
    'runningft' : IDL.Null,
  });
  const Worker = IDL.Record({
    'id' : IDL.Nat,
    'workType' : IDL.Text,
    'owner' : IDL.Principal,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'experience' : IDL.Nat,
    'mobile' : IDL.Text,
    'rateAmount' : IDL.Nat,
    'rateType' : RateType,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Rating = IDL.Record({
    'review' : IDL.Text,
    'workerId' : IDL.Nat,
    'bookingId' : IDL.Nat,
    'stars' : IDL.Nat,
    'customerId' : IDL.Principal,
  });
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'workType' : IDL.Text,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'areaSqft' : IDL.Nat,
    'customerId' : IDL.Principal,
    'calculatedPrice' : IDL.Nat,
    'startDate' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRating' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'adminGetPlatformStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalWorkers' : IDL.Nat,
            'totalBookings' : IDL.Nat,
            'completedBookings' : IDL.Nat,
            'totalRevenue' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'adminListAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'adminListAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculatePrice' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], ['query']),
    'createBooking' : IDL.Func(
        [IDL.Nat, IDL.Nat, PaymentMethod],
        [IDL.Nat],
        [],
      ),
    'createJob' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkerAverageRating' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getWorkerRatings' : IDL.Func([IDL.Nat], [IDL.Vec(Rating)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBookingsByCustomer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'listBookingsByWorker' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
    'listJobsByCustomer' : IDL.Func([IDL.Principal], [IDL.Vec(Job)], ['query']),
    'listWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'listWorkersByType' : IDL.Func([IDL.Text], [IDL.Vec(Worker)], ['query']),
    'registerWorker' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, RateType, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, Status], [], []),
    'updateWorker' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          RateType,
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };