/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : Status,
  'workerId' : bigint,
  'paymentMethod' : PaymentMethod,
  'jobId' : bigint,
  'customerId' : Principal,
  'totalPrice' : bigint,
}
export interface Job {
  'id' : bigint,
  'workType' : string,
  'description' : string,
  'address' : string,
  'areaSqft' : bigint,
  'customerId' : Principal,
  'calculatedPrice' : bigint,
  'startDate' : string,
}
export type PaymentMethod = { 'upi' : null } |
  { 'cash' : null } |
  { 'wallet' : null };
export type RateType = { 'perday' : null } |
  { 'sqft' : null } |
  { 'runningft' : null };
export interface Rating {
  'review' : string,
  'workerId' : bigint,
  'bookingId' : bigint,
  'stars' : bigint,
  'customerId' : Principal,
}
export type Status = { 'pending' : null } |
  { 'completed' : null } |
  { 'accepted' : null } |
  { 'inProgress' : null };
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Worker {
  'id' : bigint,
  'workType' : string,
  'owner' : Principal,
  'city' : string,
  'name' : string,
  'experience' : bigint,
  'mobile' : string,
  'rateAmount' : bigint,
  'rateType' : RateType,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRating' : ActorMethod<[bigint, bigint, string], undefined>,
  'adminGetPlatformStats' : ActorMethod<
    [],
    {
      'totalWorkers' : bigint,
      'totalBookings' : bigint,
      'completedBookings' : bigint,
      'totalRevenue' : bigint,
    }
  >,
  'adminListAllBookings' : ActorMethod<[], Array<Booking>>,
  'adminListAllWorkers' : ActorMethod<[], Array<Worker>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculatePrice' : ActorMethod<[string, bigint], bigint>,
  'createBooking' : ActorMethod<[bigint, bigint, PaymentMethod], bigint>,
  'createJob' : ActorMethod<[string, bigint, string, string, string], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkerAverageRating' : ActorMethod<[bigint], [] | [number]>,
  'getWorkerRatings' : ActorMethod<[bigint], Array<Rating>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBookingsByCustomer' : ActorMethod<[Principal], Array<Booking>>,
  'listBookingsByWorker' : ActorMethod<[bigint], Array<Booking>>,
  'listJobsByCustomer' : ActorMethod<[Principal], Array<Job>>,
  'listWorkers' : ActorMethod<[], Array<Worker>>,
  'listWorkersByType' : ActorMethod<[string], Array<Worker>>,
  'registerWorker' : ActorMethod<
    [string, string, string, bigint, string, RateType, bigint],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, Status], undefined>,
  'updateWorker' : ActorMethod<
    [bigint, string, string, string, bigint, string, RateType, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];